steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/imagegen', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/imagegen']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'imagegen'
      - '--image=gcr.io/$PROJECT_ID/imagegen'
      - '--platform=managed'
      - '--region=europe-west1'
      - '--allow-unauthenticated'
      - '--set-env-vars=API_KEY=MeinSuperSichererAPIKey'
images:
  - 'gcr.io/$PROJECT_ID/imagegen'
